// Conteúdo independente do formulário: perguntas reescritas para ensinar os conceitos.
const lessons = [
 {name:'HTML + JS',title:'Uma página, três responsabilidades.',text:['HTML organiza o conteúdo: títulos, parágrafos, campos e botões. CSS define a aparência. JavaScript reage às ações e modifica a página.','A tag <script> conecta o JavaScript ao documento. Colocar um script comum antes de fechar o body permite que os elementos anteriores já existam quando ele executar. Outra boa opção é usar um arquivo externo com defer no head.'],code:'<!-- No head: arquivo externo com defer -->\n<script src="script.js" defer></script>\n\n<!-- Ou no final do body: -->\n<script src="script.js"></script>',output:'defer: baixa o arquivo sem bloquear a análise do HTML e executa depois dessa análise.',tip:'<link> é usado, por exemplo, para carregar CSS. JavaScript entra com <script>. defer não tem efeito em scripts inline comuns.',summary:'HTML estrutura; CSS apresenta; JavaScript dá comportamento. Use <script> para carregar JS.'},
 {name:'Variáveis',title:'Guardar valores não é guardar só números.',text:['Uma variável tem um nome e permite acessar um valor. JavaScript aceita números, strings, booleanos, objetos e outros tipos. Com let você pode reatribuir; com const, não pode reatribuir a variável.','null representa ausência intencional de valor. undefined costuma aparecer quando ainda não há valor atribuído ou quando uma propriedade não existe. Atribuir null não apaga a variável.','Nomes podem começar com letra, _ ou $. Não podem começar com número. Maiúsculas importam: nome e Nome são identificadores diferentes.'],code:'let pontos = 10;\npontos = 20;\nlet selecionado = null;\nlet aindaSemValor; // undefined\nconst nome = "Rafael";\n// let 3vidas = 3; // nome inválido',output:'typeof null retorna "object" por uma peculiaridade histórica; null continua sendo um valor primitivo.',tip:'= atribui. === compara valor e tipo. Não use = quando pretende comparar dentro de um if.',summary:'let permite reatribuição. const impede reatribuição. null é ausência intencional; undefined é ausência de valor definido.'},
 {name:'Arrays e objetos',title:'Colchetes guardam listas; chaves descrevem.',text:['Um array é uma lista ordenada, escrita com colchetes. O primeiro item fica no índice 0, não no 1. Um objeto pode reunir propriedades com nomes e valores. Arrays também são objetos em JavaScript; não existem apenas duas categorias de objetos.','Ao acessar uma posição que não existe, o resultado é undefined. Em uma string, também podemos consultar um caractere pelo índice.'],code:'const notas = [9, 12, 20];\nconsole.log(notas[0]); // 9\nconsole.log(notas[8]); // undefined\n\nconst aluno = { nome: "Rafael", curso: "Informática" };\nconsole.log(aluno.nome); // Rafael',output:'[] indica um literal de array; { chave: valor } indica um literal de objeto.',tip:'Escreva 9, não 09. Zeros à esquerda em números podem causar problemas em determinados contextos.',summary:'Array: [9, 12, 20]. Objeto: { nome: "Rafael" }. Os índices começam em zero.'},
 {name:'DOM',title:'Encontrar primeiro. Alterar depois.',text:['DOM significa Document Object Model. É uma representação do documento em objetos, permitindo selecionar um elemento e alterar texto, estilo ou classes.','getElementById recebe o id sem # e retorna um elemento ou null. querySelector recebe um seletor CSS e retorna o primeiro elemento correspondente. getElementsByTagName retorna uma coleção.','textContent trabalha com texto. innerHTML interpreta marcação HTML; evite inserir nele conteúdo não confiável. Para campos de formulário, leia ou altere value.'],code:'const titulo = document.getElementById("titulo");\ntitulo.textContent = "Olá, Rafael!";\ntitulo.style.color = "blue";\n\nconst campo = document.querySelector("#telefone");\nconsole.log(campo.value);',output:'getElementById é singular, com E, B e I maiúsculos. getElementsbyId não existe.',tip:'style.atributo, no formulário, é uma ideia genérica. Em código real, use uma propriedade válida, como style.color.',summary:'Selecione com getElementById ou querySelector. Use textContent para texto, innerHTML para HTML e value para inputs.'},
 {name:'Eventos e classes',title:'A interação dispara a ação.',text:['Um evento é algo que acontece: clicar, digitar, mudar um campo. Um ouvinte de evento executa uma função quando isso ocorre. onclick e onchange são exemplos de atributos usados no HTML; addEventListener permite conectar a função pelo JavaScript.','input costuma ocorrer a cada alteração feita pelo usuário; change ocorre quando a alteração é confirmada, dependendo do controle. Em um campo de texto, geralmente ao sair do campo após editar.','classList.toggle adiciona uma classe ausente e remove uma classe presente. O visual muda se o CSS dessa classe definir os estilos. O JavaScript não precisa trocar o arquivo HTML.'],code:'const botao = document.querySelector("#tema");\nbotao.addEventListener("click", () => {\n  document.body.classList.toggle("dark-mode");\n});\n\n// CSS correspondente:\n// .dark-mode { background: #111; color: white; }',output:'Primeiro clique: adiciona dark-mode. Segundo clique: remove dark-mode.',tip:'classList é uma propriedade; querySelector é um método. Não confunda com eventos como click e change.',summary:'Eventos ligam interações a funções. toggle alterna a presença de uma classe; CSS determina o visual.'},
 {name:'Strings e soma',title:'O sinal de + tem dois trabalhos.',text:['Entre números, + soma. Se um dos operandos for string, + pode concatenar, ou seja, juntar textos. Em uma sequência de +, a avaliação segue da esquerda para a direita. Parênteses podem mudar a ordem.','slice(inicio, fim) extrai uma parte de uma string, incluindo inicio e excluindo fim. Ele não altera a string original; retorna outra. replace substitui; toUpperCase converte para maiúsculas; charAt consulta um caractere.'],code:'10 + 20 + 11 + "lol"; // "41lol"\n"10" + 20 + 11;       // "102011"\n"total: " + (10 + 20); // "total: 30"\n\nconst texto = "Rafael";\ntexto.slice(0, 3); // "Raf"\ntexto.toUpperCase(); // "RAFAEL"',output:'"10" é texto. 10 é número. As aspas fazem diferença.',tip:'Na questão do formulário, Var está escrito incorretamente. A palavra-chave válida é var, com v minúsculo.',summary:'Números somam; strings concatenam. slice(0, 3) retorna os caracteres nas posições 0, 1 e 2.'},
 {name:'Saídas e modal',title:'Cada saída tem um lugar.',text:['console.log mostra valores no console de desenvolvimento, útil para observar o estado do código. alert mostra uma caixa de aviso do navegador. Nenhum deles altera automaticamente o texto de um parágrafo.','showModal é um método de elementos <dialog>. Ele abre o diálogo em modo modal, deixando o restante da página inerte enquanto estiver aberto. Use close para fechá-lo. Não é um método de qualquer div.'],code:'console.log("Valor para depurar", 10);\nwindow.alert("Aviso ao usuário");\n\n// HTML: <dialog id="aviso">Olá!</dialog>\nconst dialogo = document.getElementById("aviso");\ndialogo.showModal();\n// Para fechar: dialogo.close();',output:'Console: ferramenta de desenvolvimento. Alert: caixa do navegador. Dialog: elemento HTML.',tip:'console.log aceita strings, números, objetos, elementos e vários argumentos — não apenas variáveis.',summary:'console.log → console; alert → caixa de alerta; showModal → abre um <dialog>.'},
 {name:'Telefone e armazenamento',title:'Limitar, formatar e salvar são ações diferentes.',text:['tel.slice(0,14) retorna no máximo os primeiros 14 caracteres. Ao atribuir o resultado ao campo, o texto fica limitado. Isso não remove letras e não acrescenta parênteses ou hífen.','Uma máscara organiza a exibição, por exemplo (31)99999-9999. Verificar tel_formatado[0] !== undefined evita usar um primeiro caractere inexistente. A máscara não prova que o telefone existe ou é válido.','localStorage.setItem(chave, valor) salva texto no navegador para aquela origem. getItem(chave) lê e retorna null quando a chave não existe. Os dados podem persistir após fechar o navegador, mas podem ser apagados ou bloqueados.'],code:'const campo = document.getElementById("telefone");\nconst limitado = campo.value.slice(0, 14);\ncampo.value = limitado;\n\nlocalStorage.setItem("telefone", campo.value);\nconst salvo = localStorage.getItem("telefone");\n// Remove somente essa chave:\nlocalStorage.removeItem("telefone");',output:'setItem salva; getItem lê; removeItem apaga uma chave. Os valores são armazenados como strings.',tip:'No código da prova, tel_formatado pode conter um valor anterior à última alteração do campo. Para salvar a versão atual, leia campo.value novamente.',summary:'slice limita o tamanho; máscara formata; localStorage armazena. São responsabilidades diferentes.'}
];
const tips = [
 ['Não decore um erro do enunciado','A alternativa de soma começa com Var. A intenção é somar 10 + 20 + 11 e depois juntar "lol", mas código JavaScript válido usa var.'],
 ['null não faz a variável desaparecer','“Esvazia o conteúdo” é a alternativa aproximada do formulário. O conceito preciso é atribuir um valor que representa ausência intencional.'],
 ['Script no head também pode estar certo','Um script externo com defer executa após a análise do HTML e mantém a ordem entre scripts defer. A opção “fim do body” é a melhor entre as oferecidas no formulário.'],
 ['A primeira posição é zero','tel[0] consulta o primeiro caractere. tel[1] consulta o segundo. Em uma string vazia, tel[0] é undefined.'],
 ['A última questão tem alternativas equivalentes nesse caso','A resposta com != undefined segue o padrão apresentado. Mas != null também aceita ausência de null/undefined; e, nesse acesso a uma string, testar o caractere diretamente também detecta sua existência. Não trate a pergunta como exemplo de alternativa única perfeita.'],
 ['Limite de caracteres não é máscara','slice(0,14) só corta o texto. Não impede letras, não adiciona pontuação e não valida um número de telefone.'],
 ['Confira a grafia dos métodos','getElementById é singular. getElementsByTagName é plural. JavaScript diferencia maiúsculas de minúsculas.'],
 ['O conteúdo do campo pode mudar sem atualizar a variável','Se você leu campo.value e depois mudou campo.value, a string guardada anteriormente na variável não se atualiza sozinha. Leia o campo de novo antes de salvar.']
];
// Cada questão possui justificativa da resposta e feedback específico para cada erro.
const questions = [
 {t:0,q:'Qual tag carrega JavaScript em uma página HTML?',o:['<link>','<script>','<style>','<input>'],a:1,why:'<script> insere ou carrega JavaScript. Um arquivo externo pode usar src.',wrong:['<link> relaciona recursos, como uma folha CSS.','','<style> contém CSS, não JavaScript.','<input> cria um controle de entrada.']},
 {t:0,q:'Um script externo no head precisa usar os elementos do HTML sem bloquear sua análise. Qual opção atende a isso?',o:['Colocar antes de <!DOCTYPE>','Usar uma tag <link>','Adicionar defer ao <script>','Renomear o arquivo para .html'],a:2,why:'defer adia a execução até depois da análise do documento, mantendo o download em paralelo.',wrong:['Isso não é a solução correta para controlar a execução.','<link> não executa o arquivo JavaScript.','','A extensão não resolve o momento de execução.']},
 {t:2,q:'Qual declaração cria um array?',o:['const notas = [9, 12, 20];','const notas = 9;','const notas = "9, 12, 20";','const notas = { media: 9 };'],a:0,why:'Um literal de array usa colchetes, e seus elementos ficam em posições numeradas a partir de zero.',wrong:['','Isso guarda um número.','Isso guarda uma única string.','Isso cria um objeto com a propriedade media.']},
 {t:3,q:'O que significa DOM?',o:['Document Oriented Module','Data Object Method','Document Observer Model','Document Object Model'],a:3,why:'DOM significa Document Object Model, a representação do documento em objetos acessíveis por programação.',wrong:['Oriented Module não faz parte do nome.','Não é Data Object Method.','Observer não faz parte da sigla.','']},
 {t:1,q:'Depois de let selecionado = null, o que é verdade?',o:['A variável foi apagada','A variável guarda ausência intencional de valor','O valor é o número zero','O código tem erro de sintaxe'],a:1,why:'null é um valor primitivo que representa ausência intencional. A variável segue existindo.',wrong:['Atribuir null não remove a declaração da variável.','','null não é o número 0, mesmo que algumas coerções possam confundir.','null é uma palavra válida em JavaScript.']},
 {t:4,q:'O que classList.toggle("dark-mode") faz?',o:['Troca o arquivo HTML','Escurece automaticamente qualquer cor','Adiciona ou remove a classe dark-mode','Renomeia o id para dark-mode'],a:2,why:'toggle alterna a presença da classe. As regras CSS associadas à classe produzem o efeito visual.',wrong:['Não há troca do documento.','O efeito depende de regras CSS; o método não calcula cores.','','Classes e id são atributos diferentes.']},
 {t:6,q:'Em qual elemento showModal() é usado para abrir um modal?',o:['<dialog>','<div>','<span>','<input>'],a:0,why:'showModal é um método de HTMLDialogElement, representado pela tag <dialog>.',wrong:['','Uma div não possui esse método nativamente.','Um span não possui esse método nativamente.','Um input não é um diálogo.']},
 {t:4,q:'Qual opção liga a edição de um campo a uma ação?',o:['O atributo name, sozinho','Um evento e sua função de tratamento','A extensão .html','Uma cor de fundo'],a:1,why:'Eventos como input e change permitem chamar funções quando o usuário modifica o campo.',wrong:['name identifica o campo, mas não executa uma função sozinho.','','A extensão não registra um comportamento.','CSS altera aparência, não registra esse tratamento.']},
 {t:4,q:'Qual alternativa é um atributo de tratamento de evento?',o:['classList','querySelector','getElementById','onchange'],a:3,why:'onchange permite tratar o evento change. No JavaScript, também é possível usar addEventListener.',wrong:['classList permite manipular classes.','querySelector seleciona elementos.','getElementById seleciona um elemento pelo id.','']},
 {t:3,q:'Qual chamada contém um nome de método inexistente?',o:['document.getElementById("nome")','document.querySelector("#nome")','document.getElementsbyId("nome")','document.getElementsByTagName("p")'],a:2,why:'getElementsbyId não existe. O método correto é getElementById.',wrong:['Essa chamada tem a grafia correta.','Essa chamada usa corretamente um seletor CSS.','','Essa chamada existe e retorna uma coleção.']},
 {t:5,q:'Qual é o resultado da expressão?',code:'10 + 20 + 11 + "lol"',o:['"102011lol"','"41lol"','41','Erro: número e string não podem usar +'],a:1,why:'As três primeiras parcelas são numéricas e somam 41. Depois, a string provoca concatenação.',wrong:['Isso aconteceria se a concatenação começasse antes das somas.','','O "lol" é concatenado; o resultado final é texto.','O operador + permite concatenação com conversão para string.']},
 {t:5,q:'O que "Rafael".slice(0, 3) retorna?',o:['"Raf"','"Rafa"','"afa"','"Rafael"'],a:0,why:'O início 0 é incluído e o fim 3 é excluído: posições 0, 1 e 2 formam Raf.',wrong:['','O índice final não entra no trecho.','O início é 0, então R entra.','O trecho termina antes do índice 3.']},
 {t:7,q:'Qual efeito este código produz?',code:'campo.value = campo.value.slice(0, 14);',o:['Adiciona parênteses e hífen','Remove tudo que não for número','Confirma que o telefone existe','Mantém no máximo 14 caracteres'],a:3,why:'slice seleciona os primeiros 14 caracteres. A atribuição coloca esse trecho de volta no campo.',wrong:['Não há instruções acrescentando pontuação.','slice não filtra letras nem símbolos.','Não há nenhuma validação de existência do telefone.','']},
 {t:6,q:'Qual associação está correta?',o:['alert → console; log → modal','log → parágrafo; alert → PDF','alert → caixa de alerta; log → console','Ambos alteram automaticamente o body'],a:2,why:'window.alert abre uma caixa de aviso; console.log escreve no console de desenvolvimento.',wrong:['Os destinos foram confundidos.','Nenhum desses métodos gera PDF ou atualiza um parágrafo automaticamente.','','Para mudar o body, é preciso manipular o DOM.']},
 {t:3,q:'Para mostrar texto digitado pelo usuário em um parágrafo sem interpretar tags, o que usar?',o:['innerHTML','textContent','showModal','classList'],a:1,why:'textContent trata a entrada como texto. innerHTML interpretaria marcação e exige cuidado com conteúdo não confiável.',wrong:['innerHTML interpreta tags, contrariando o objetivo.','','showModal abre diálogos.','classList manipula classes, não o texto.']},
 {t:1,q:'Qual nome de variável é inválido?',o:['3var1avel','_variavel','$variavel','Variavel'],a:0,why:'Identificadores não podem começar com um dígito. Letras, _ e $ são permitidos no início.',wrong:['','O sublinhado é permitido.','O cifrão é permitido.','Letras maiúsculas são permitidas.']},
 {t:7,q:'Como salvar a string tel_formatado no navegador com a chave telefone?',o:['localStorage.getItem("telefone")','localStorage.setItem(telefone: tel_formatado)','localStorage.getItem("telefone", tel_formatado)','localStorage.setItem("telefone", tel_formatado)'],a:3,why:'setItem recebe dois argumentos separados por vírgula: a chave e o valor a salvar.',wrong:['getItem lê dados; não salva.','Dois-pontos não separam argumentos de função.','getItem não usa um segundo argumento para salvar.','']},
 {t:7,q:'Para uma string tel, qual comparação estrita verifica se existe um primeiro caractere?',o:['tel[1] !== undefined','tel[0] = undefined','tel[0] !== undefined','tel === null'],a:2,why:'O primeiro caractere fica no índice 0. !== compara sem atribuir e sem coerção de tipos.',wrong:['Índice 1 consulta o segundo caractere.','= é atribuição, não comparação.','','Testar a string inteira contra null não verifica o primeiro caractere.']}
];
// Função utilitária para localizar os elementos da interface.
const $ = id => document.getElementById(id);
const esc = text => String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setView(id){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==id);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===id)));}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
function showLesson(index){const l=lessons[index];document.querySelectorAll('[data-topic]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.topic)===index)));$('lesson').innerHTML=`<p class="eyebrow">TEMA ${String(index+1).padStart(2,'0')}</p><h3>${esc(l.title)}</h3>${l.text.map(p=>`<p>${esc(p)}</p>`).join('')}<pre><code>${esc(l.code)}</code></pre><p class="result-line">${esc(l.output)}</p><p class="remember"><strong>Para lembrar:</strong> ${esc(l.tip)}</p><div class="lesson-actions"><button class="primary" id="practice">Praticar no quiz</button></div>`;$('practice').addEventListener('click',()=>setView('quiz'));}
$('topic-tabs').innerHTML=lessons.map((l,i)=>`<button data-topic="${i}" aria-pressed="false">${esc(l.name)}</button>`).join('');
document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>showLesson(Number(b.dataset.topic))));
$('summary-grid').innerHTML=lessons.map((l,i)=>`<article class="summary-card"><p class="eyebrow">0${i+1}</p><h3>${esc(l.name)}</h3><p>${esc(l.summary)}</p></article>`).join('');
$('tips').innerHTML=tips.map((t,i)=>`<article class="tip"><b>${String(i+1).padStart(2,'0')}</b><div><h3>${esc(t[0])}</h3><p>${esc(t[1])}</p></div></article>`).join('');
// O progresso do quiz permanece enquanto a página está aberta; não há envio de dados.
let sequence=questions.map((_,i)=>i), position=0, answers=[], locked=false;
function renderQuestion(){locked=false;const q=questions[sequence[position]];$('question-area').hidden=false;$('result').hidden=true;$('question-count').textContent=`QUESTÃO ${position+1} / ${sequence.length}`;$('question-topic').textContent=lessons[q.t].name;$('progress').max=sequence.length;$('progress').value=answers.length;$('score').textContent=`${answers.filter(a=>a.correct).length} acertos`;$('question').textContent=q.q;$('question-code').hidden=!q.code;$('question-code').querySelector('code').textContent=q.code||'';$('feedback').replaceChildren();$('next').hidden=true;$('options').innerHTML=q.o.map((o,i)=>`<button type="button"><b>${'ABCD'[i]}</b><span>${esc(o)}</span></button>`).join('');Array.from($('options').children).forEach((b,i)=>b.addEventListener('click',()=>answer(i)));}
function answer(choice){if(locked)return;locked=true;const id=sequence[position],q=questions[id],correct=choice===q.a;answers.push({id,choice,correct});Array.from($('options').children).forEach((b,i)=>{b.disabled=true;if(i===q.a){b.classList.add('correct');b.querySelector('span').textContent+=' — correta';}else if(i===choice){b.classList.add('wrong');b.querySelector('span').textContent+=' — sua resposta';}});$('feedback').innerHTML=`<strong>${correct?'Isso mesmo!':'Vamos entender.'}</strong>${correct?'':`<p><b>Sua alternativa:</b> ${esc(q.wrong[choice])}</p>`}<p><b>Por que a correta funciona:</b> ${esc(q.why)}</p>`;$('progress').value=answers.length;$('score').textContent=`${answers.filter(a=>a.correct).length} acertos`;$('next').textContent=position===sequence.length-1?'Ver resultado':'Próxima questão';$('next').hidden=false;}
$('next').addEventListener('click',()=>{position++;if(position<sequence.length){renderQuestion();$('question').focus({preventScroll:true});}else showResult();});
function showResult(){const hits=answers.filter(a=>a.correct).length,misses=answers.filter(a=>!a.correct);$('question-area').hidden=true;$('result').hidden=false;$('question-count').textContent='REVISÃO CONCLUÍDA';$('question-topic').textContent='Seu resultado';$('result-title').textContent=`${hits} de ${sequence.length} acertos`;$('result-copy').textContent=misses.length?'Revise as explicações abaixo e tente novamente as questões em que teve dificuldade.':'Você acertou todas nesta rodada. Tente explicar os conceitos com suas próprias palavras antes de repetir.';$('review-errors').innerHTML=misses.map(a=>{const q=questions[a.id];return `<details><summary>${esc(q.q)}</summary><p>Sua resposta: ${esc(q.o[a.choice])}</p><p>Correta: ${esc(q.o[q.a])}</p><p>${esc(q.why)}</p></details>`;}).join('');$('retry-errors').hidden=!misses.length;$('result-title').focus({preventScroll:true});}
function restart(ids){sequence=ids;position=0;answers=[];renderQuestion();$('question').focus({preventScroll:true});}
$('restart').addEventListener('click',()=>restart(questions.map((_,i)=>i)));
$('retry-errors').addEventListener('click',()=>restart(answers.filter(a=>!a.correct).map(a=>a.id)));
showLesson(0);renderQuestion();
// Integração opcional do navegador; o site funciona normalmente sem esse recurso.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{ /* Recurso opcional indisponível. */ }};
 register({name:'read_quiz_progress',description:'Lê o progresso atual da rodada, sem revelar respostas futuras.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({answered:answers.length,total:sequence.length,hits:answers.filter(a=>a.correct).length,completed:position>=sequence.length})});
 register({name:'answer_current_question',description:'Marca uma alternativa na questão atual do quiz local e mostra a correção, sem enviar dados.',inputSchema:{type:'object',properties:{questionNumber:{type:'integer',minimum:1},choice:{type:'integer',minimum:1,maximum:4}},required:['questionNumber','choice'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Number.isInteger(input.choice)||input.choice<1||input.choice>4||input.questionNumber!==position+1||position>=sequence.length||locked)throw new Error('Questão ou alternativa inválida, ou questão já respondida.');setView('quiz');answer(input.choice-1);return {correct:answers.at(-1).correct,explanation:questions[sequence[position]].why};}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
